### ISSUE TITLE
[Feature request] Add a scroll to bottom button

### ISSUE THREAD

**Issue by pcuellar** [cloudhao1999/obsidian-scroll-to-top-plugin#1]
Such a simple, yet useful plugin. I love it! As a writer of long notes, it would be very helpful to have a scroll to bottom option. Notes open at the top by default and you have to scroll your way back if you want to write at the bottom.

**Comment by cloudhao1999** [comment]
The lastest version 1.1.0 adds the feature of the bottom button

**Comment by pcuellar** [comment]
It looks great, thanks for adding that up. One little thing from an interaction/accessibility point of view: the user expectation is for arrows to be visually placed in the direction they function. Right now your ⬆️  **going up** arrow under the ⬇️ **going down** which, if you take the interface of a remote control as an example, would be the reverse order. Probably you meant it this way, but thought I'd still mention it in case is useful.

**Comment by cloudhao1999** [comment]
> It looks great, thanks for adding that up. One little thing from an interaction/accessibility point of view: the user expectation is for arrows to be visually placed in the direction they function. Right now your ⬆️ **going up** arrow under the ⬇️ **going down** which, if you take the interface of a remote control as an example, would be the reverse order. Probably you meant it this way, but thought I'd still mention it in case is useful.

What you said is quite right. I will revise it in the next version. Thank you for your advice ！
