### ISSUE TITLE
跟浏览器插件联动

### ISSUE THREAD

**Issue by grisbear** [cloudhao1999/obsidian-scroll-to-top-plugin#10]
最近有 [Surfing](https://github.com/Quorafind/Obsidian-Surfing) 插件，不知道作者，能不能支持网页。

**Comment by cloudhao1999** [comment]
> 最近有 [Surfing](https://github.com/Quorafind/Obsidian-Surfing) 插件，不知道作者，能不能支持网页。

最近有亿点点忙，等这段加班完我看一下

**Comment by cloudhao1999** [comment]
> 最近有 [Surfing](https://github.com/Quorafind/Obsidian-Surfing) 插件，不知道作者，能不能支持网页。

久等了（确实挺久的，不是我懒是真的加班很严重），最新版本 1.6.0 已经兼容该插件，现在可以在 Obsidian 中控制浏览器的滚动了，感谢你对本插件的支持～
