### ISSUE TITLE
[Feature request]: Support Minimal Theme

### ISSUE THREAD

**Issue by merlinuwe** [cloudhao1999/obsidian-scroll-to-top-plugin#13]
Thanks for your great plugin.

I suggest to support Minimal Theme too, because it is widely used and your plugin is so useful ;-)

**Comment by cloudhao1999** [comment]
This is an excellent theme. Is there any incompatibility between this plugin and the theme?

**Comment by merlinuwe** [comment]
Yes, I see no arrows.

**Comment by cloudhao1999** [comment]
> 

I installed the Minimal theme and Scroll To Top plugin on my Windows, but did not find arrow missing

<img width="1440" alt="image" src="https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/assets/32376445/c41084c5-0042-4794-8cb1-c5414ea361e5">

You can check if the plugin is enabled or if there may be conflicts with other plugins. The icon may not appear when the Obsidian first starts, and you need to manually click on the view

<img width="1440" alt="image" src="https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/assets/32376445/37329031-80a2-45c2-a7a7-457a19fffc80">

<img width="1440" alt="image" src="https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/assets/32376445/06f539e3-313b-44c2-8ffa-e0be95eac267">
