### ISSUE TITLE
[bug] when a note is pinned, click a link to jump other note, obsidian will stuck 

### ISSUE THREAD

**Issue by doit132** [cloudhao1999/obsidian-scroll-to-top-plugin#16]
# Question description

when a note is pinned, click a link to jump other note, obsidian will stuck 

# Animation demonstration

![动画-tuya](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/assets/117004316/3aa438a1-0555-4735-a9ee-a869c06a5ed2)

# testing environment

- obsidian sandbox vault
- v1.3.5

**Comment by cloudhao1999** [comment]
> # Question description
> when a note is pinned, click a link to jump other note, obsidian will stuck
> 
> # Animation demonstration
> ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> 
> # testing environment
> * obsidian sandbox vault
> * v1.3.5

Sorry for the unpleasant experience. Version 2.0.1 has fixed this issue. You can update it

**Comment by doit132** [comment]
> > # Question description
> > when a note is pinned, click a link to jump other note, obsidian will stuck
> > # Animation demonstration
> > ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> >       
> >         [
> >           
> >         
> >             ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> >           ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> >         
> >       
> > # testing environment
> > 
> > * obsidian sandbox vault
> > * v1.3.5
> 
> Sorry for the unpleasant experience. Version 2.0.1 has fixed this issue. You can update it

Automatically appear a new tab

![动画-tuya](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/assets/117004316/1b67817c-e8de-43a4-8e13-70fd801fe1d8)

**Comment by cloudhao1999** [comment]
> > > # Question description
> > > when a note is pinned, click a link to jump other note, obsidian will stuck
> > > # Animation demonstration
> > > ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >       
> > >         [
> > >           
> > >         
> > >             ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >           ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >     
> > >         ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >       ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > # testing environment
> > > 
> > > * obsidian sandbox vault
> > > * v1.3.5
> > 
> > 
> > Sorry for the unpleasant experience. Version 2.0.1 has fixed this issue. You can update it
> 
> Automatically appear a new tab
> 
> ![动画-tuya](https://user-images.githubusercontent.com/117004316/251065719-1b67817c-e8de-43a4-8e13-70fd801fe1d8.gif)

I have also discovered this issue and am looking for a solution, which will be resolved in version 2.0.2

**Comment by cloudhao1999** [comment]
> > > # Question description
> > > when a note is pinned, click a link to jump other note, obsidian will stuck
> > > # Animation demonstration
> > > ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >       
> > >         [
> > >           
> > >         
> > >             ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >           ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >     
> > >         ![动画-tuya](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >       ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/117004316/251056496-3aa438a1-0555-4735-a9ee-a869c06a5ed2.gif)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > # testing environment
> > > 
> > > * obsidian sandbox vault
> > > * v1.3.5
> > 
> > 
> > Sorry for the unpleasant experience. Version 2.0.1 has fixed this issue. You can update it
> 
> Automatically appear a new tab
> 
> ![动画-tuya](https://user-images.githubusercontent.com/117004316/251065719-1b67817c-e8de-43a4-8e13-70fd801fe1d8.gif)

The latest version 2.0.2 has fixed the issue of automatically popping up new tabs. You can download the latest version and try it out. Thank you for your support～

**Comment by 1C0D** [comment]
wow, it was a nasty bug the freezing. 😅
