### ISSUE TITLE
[Feature request] Adding styling settings support

### ISSUE THREAD

**Issue by pcuellar** [cloudhao1999/obsidian-scroll-to-top-plugin#2]
Some users like to have full control over how their themes look like. Adding a few styling settings will go a long way here. A few that come to mind:
- Change the icon of the button
- Change size/position of the button
- Change the text next to the button (along with an option to hide the text)

You can add these on your plugin options or as part of the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by cloudhao1999** [comment]
Thanks for your comments！I just got in touch with the development of Obsidian plugin today. I will seriously consider these functions

**Comment by cloudhao1999** [comment]
> Some users like to have full control over how their themes look like. Adding a few styling settings will go a long way here. A few that come to mind:
> 
> * Change the icon of the button
> * Change size/position of the button
> * Change the text next to the button (along with an option to hide the text)
> 
> You can add these on your plugin options or as part of the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

The latest 1.3.0 version adds the above new features, thanks for your suggestion 🤟

**Comment by pcuellar** [comment]
Hey @cloudhao1999, the plugin looks super neat, I have been using it heavily, appreciate you developing it. Great work!
