### ISSUE TITLE
failed to load plugin obsidian-scroll-to-top-plugin

### ISSUE THREAD

**Issue by merlinuwe** [cloudhao1999/obsidian-scroll-to-top-plugin#21]
Thanks for your great plugin.

After installing, the plugin works. But when I restart Obsidian, a message in the upper right appears and says "failed to load plugin obsidian-scroll-to-top-plugin".

When I reinstall, it works, but only as long as I don't restart Obsidian.

It runs in the sandbox. Are there any knows incompatibilities with one of the following plugins? 

I use Minimal Theme.

	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 62
	Restricted mode: off
	Plugins installed: 96
	Plugins enabled: 60
		1: Vault Statistics v0.1.3
		2: Unicode Search v0.4.1
		3: Typing Transformer v0.4.0
		4: Text Extractor v0.4.6
		5: Templater v1.16.0
		6: Tasks v4.4.0
		7: Tag & Word Cloud v1.3.2
		8: Symbols Prettifier v1.1.1
		9: Supercharged Links v0.9.7
		10: Style Settings v1.0.6
		11: Sidebar Expand on Hover v1.0.1
		12: Show Current File Path v0.5.2
		13: Recent Files v1.3.7
		14: Reading View Enhancer v0.1.4
		15: Quiet Outline v0.3.15
		16: Quick Explorer v0.2.8
		17: Plotly v0.0.6
		18: Paste image rename v1.6.1
		19: Omnisearch v1.15.2
		20: Obsidian Link Converter v0.1.4
		21: Obsidian Enhancing Export v1.8.4
		22: Obsidian Camera v1.5.0
		23: Number Headings v1.13.0
		24: Minimal Theme Settings v6.3.2
		25: Mathpad v0.8.14
		26: Linter v1.18.0
		27: Link Archive v0.2.0
		28: Kroki v1.2.3
		29: Image Layouts v0.10.0
		30: Icon Folder v2.1.2
		31: Hover Editor v0.11.13
		32: Homepage v3.3.3
		33: Global Search and Replace v0.3.0
		34: Fullscreen mode plugin v0.1.2
		35: File Explorer Note Count v1.2.1
		36: Export Image plugin v1.0.3
		37: Execute Code v1.8.1
		38: Excel to Markdown Table v0.4.0
		39: Editor Syntax Highlight v0.1.3
		40: Editing Toolbar v2.3.1
		41: Dictionary v2.22.0
		42: Desmos v0.6.6
		43: Dataview v0.5.56
		44: Custom Classes v2.6.1
		45: Creases v0.7.0
		46: Copy document as HTML v0.5.0
		47: Completr v3.2.0
		48: Commander v0.5.0
		49: Colorful Note Borders v0.2.4
		50: Codeblock Customizer v1.1.9
		51: Chronology v1.1.7
		52: Chem v0.2.0
		53: Charts View v1.2.5
		54: Buttons v0.4.19
		55: Auto Glossary v0.9.0
		56: Auto Class v2.3.0
		57: Audio Player v0.1.1
		58: Advanced URI v1.36.4
		59: Admonition v9.3.3
		60: Scroll to Top Plugin v2.1.2

**Comment by cloudhao1999** [comment]
I cannot reproduce this issue on my Windows device, but I can provide a few points for your reference:
- It may be influenced by other plugins. Try disabling the remaining plugins to troubleshoot.
- Find the cause of the error. You can open the console to view specific error messages.
- Completely remove the plugin. You can try clicking 'Open plugins folder' to locate and delete the plugin.
- It could be due to system issues. Restart your computer, relaunch Obsidian, and reinstall the plugin.
