### ISSUE TITLE
Plugin fails to load on mobile

### ISSUE THREAD

**Issue by mathisgauthey** [cloudhao1999/obsidian-scroll-to-top-plugin#24]
Hi there, using the last version of obsidian and your plugin. I'm having issues where the plugin fails to load sometimes, even though there weren't any issues at first.

I don't know what might cause it, I'm using obsidian on an Android 13 device (Google Pixel 7).

Thanks !

**Comment by cloudhao1999** [comment]
I see. I'm on vacation recently. I'll look into it after my vacation

**Comment by mathisgauthey** [comment]
To add a little bit of information, it seems like it only does that when there was no open page on previous obsidian closing.

If I open it and I have a note opened there's no issue apparently. 👍

**Comment by Jack-Chronicle** [comment]
Reloading the plugin with a note open also seems to fix it, but is annoying to have to always do
May have to do with loading the plugin without an open note?

**Comment by mathisgauthey** [comment]
Hey @cloudhao1999, I hope I'm not bothering you, but have you had time to check out if there's a simple fix ?

I see there's another [issue](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/issues/25) that relates to the same problem (#25).

**Comment by cloudhao1999** [comment]
> Hey @cloudhao1999, I hope I'm not bothering you, but have you had time to check out if there's a simple fix ?
> 
> I see there's another [issue](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/issues/25) that relates to the same problem (#25).

I'm sorry for waiting so long. This is indeed a minor issue. I just returned from a business trip and the latest version has resolved the error reporting issue. Thank you for your patience and patience～

**Comment by mathisgauthey** [comment]
> > Hey @cloudhao1999, I hope I'm not bothering you, but have you had time to check out if there's a simple fix ?
> > 
> > I see there's another [issue](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/issues/25) that relates to the same problem (#25).
> 
> I'm sorry for waiting so long. This is indeed a minor issue. I just returned from a business trip and the latest version has resolved the error reporting issue. Thank you for your patience and patience～

That's completely fine you don't owe us nothing, thanks a lot for your work here ! Wish you the best. 👍
