### ISSUE TITLE
Opening Obsidian when no file is open: "Failed to load plugin"

### ISSUE THREAD

**Issue by redactedscribe** [cloudhao1999/obsidian-scroll-to-top-plugin#25]
When opening Obsidian and there isn't a note open (tab says "New tab" and the content is "No file is open"), Scroll to Top fails to load. To fix this for the current session, you have to go to the community plugins, disable and re-enabled the plugin.

Thanks.

**Edit:** The same happens if the graph view / canvas is what was last open before closing and then re-opening Obsidian.

**Edit 2:** Also happens if the Search tab is open instead of the Files tab. Try disabling and re-enabling the plugin with the Search tab open with a document open in a tab (the scroll buttons will not appear).

**Comment by merlinuwe** [comment]
Yes, well analyzed. ;-)

**Comment by cloudhao1999** [comment]
Sorry for keeping you waiting for so long. I just came back from a business trip and the latest version has already resolved this issue

**Comment by redactedscribe** [comment]
Thanks for the fix @cloudhao1999. I have updated the plugin and will let you know if the bug appears again.

**Comment by merlinuwe** [comment]
It works again! Thank you soooo much!
