### ISSUE TITLE
编辑模式下，没有置顶，只是到编辑内容的顶部，优化下。

### ISSUE THREAD

**Issue by grisbear** [cloudhao1999/obsidian-scroll-to-top-plugin#4]
https://github.com/SkepticMystic/breadcrumbs
这个插件，会在页面顶部添加导航栏，
![image](https://user-images.githubusercontent.com/74553083/200265574-9e6e1e71-96e4-4223-a8ca-876110dfa06a.png)
而编辑模式的状态下，你的插件只能到内容的顶部，而不是页面顶部。
![`ZXP36MDSOHQ9X${8HBKCII](https://user-images.githubusercontent.com/74553083/200265949-a5ac01a3-e3bc-4931-8ad4-4b803aab33e0.png)

**Comment by cloudhao1999** [comment]
> https://github.com/SkepticMystic/breadcrumbs 这个插件，会在页面顶部添加导航栏， ![image](https://user-images.githubusercontent.com/74553083/200265574-9e6e1e71-96e4-4223-a8ca-876110dfa06a.png) 而编辑模式的状态下，你的插件只能到内容的顶部，而不是页面顶部。 ![`ZXP36MDSOHQ9X${8HBKCII](https://user-images.githubusercontent.com/74553083/200265949-a5ac01a3-e3bc-4931-8ad4-4b803aab33e0.png)

感谢你的建议，我之前装了个隐藏滚动条的插件所以没怎么注意，我已经修改了编辑模式滚动到顶部的逻辑，你可以更新1.4.1版本试试看，插件已经加入社区插件市场中，可以在obsidian中搜索 `Scroll to Top Plugin` 安装，谢谢你的提议 🚀

**Comment by grisbear** [comment]
> > https://github.com/SkepticMystic/breadcrumbs 这个插件，会在页面顶部添加导航栏， ![image](https://user-images.githubusercontent.com/74553083/200265574-9e6e1e71-96e4-4223-a8ca-876110dfa06a.png) 而编辑模式的状态下，你的插件只能到内容的顶部，而不是页面顶部。 ![`ZXP36MDSOHQ9X${8HBKCII](https://user-images.githubusercontent.com/74553083/200265949-a5ac01a3-e3bc-4931-8ad4-4b803aab33e0.png)
> 
> 感谢你的建议，我之前装了个隐藏滚动条的插件所以没怎么注意，我已经修改了编辑模式滚动到顶部的逻辑，你可以更新1.4.1版本试试看，插件已经加入社区插件市场中，可以在obsidian中搜索 `Scroll to Top Plugin` 安装，谢谢你的提议 🚀

嗯嗯，新版可以了 👍
