### ISSUE TITLE
FR: Add what icon set plugin uses by default to documentation 

### ISSUE THREAD

**Issue by brimwats** [cloudhao1999/obsidian-scroll-to-top-plugin#5]
Does this plugin use obsidian's built in lucide icons? so I could use arrow-up-circle?

**Comment by cloudhao1999** [comment]
> Does this plugin use obsidian's built in lucide icons? so I could use arrow-up-circle?

Version 1.4.2 changed the link to get the icon

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/32376445/201452782-dfb9af1c-c1f5-4286-b95c-ccf083050d52.png">
