### ISSUE TITLE
FR: Toggle to combine the up/down button 

### ISSUE THREAD

**Issue by brimwats** [cloudhao1999/obsidian-scroll-to-top-plugin#6]
Ideally using icon arrow-up-down, the plugin would detect if it was at the bottom or top of a note and pushing the button would take you to the opposite of where you were. if user was in the middle it'd default to top, or be configurable

**Comment by cloudhao1999** [comment]
This is a good suggestion, but I am not sure whether the existing API can be well supported. I will consider it carefully
