### ISSUE TITLE
Expose command to Obsidian

### ISSUE THREAD

**Issue by feedhopper** [cloudhao1999/obsidian-scroll-to-top-plugin#7]
Can the two buttons please be exposed to Obsidian so that we can add them to menus like Editing Toolbar"?

https://github.com/cumany/obsidian-editing-toolbar

The second little menu seems to always be in the way. It would be great to have this integrated.

**Comment by cloudhao1999** [comment]
Thank you for your advice. I will try to realize your needs, which may take some time 🤟

**Comment by cloudhao1999** [comment]
> Can the two buttons please be exposed to Obsidian so that we can add them to menus like Editing Toolbar"?
> 
> https://github.com/cumany/obsidian-editing-toolbar
> 
> The second little menu seems to always be in the way. It would be great to have this integrated.

The latest version 1.5.0 exposes two commands to Obsidian, You can associate these commands
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/32376445/201561527-b646f271-2027-4728-b98d-e73b1324b9d4.png">
