### ISSUE TITLE
大佬， 请问您Obsidian用的是什么主题？

### ISSUE THREAD

**Issue by nevertoday** [cloudhao1999/obsidian-scroll-to-top-plugin#8]
Thank u so much!

**Comment by cloudhao1999** [comment]
是官方的主题加上我朋友自己diy的css片段，解压后替换一下原有的css，然后重启一下软件
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/32376445/202071222-9275bef4-ccce-424f-a0c0-11976a0f8232.png">

[default.css.zip](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/files/10017692/default.css.zip)

**Comment by nevertoday** [comment]
好想求这个setting panel 部分透明的代码， if 方便的话，谢谢。 我找到了插件，所有页面都透明了， 并非我想要的！
你底部的图片有巧思~ 这个山的部分，很低调，舒适。 能不能干脆share 我css ？ 
Thank u so much!

**Comment by cloudhao1999** [comment]
[default.txt](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/files/10017960/default.txt)

**Comment by cloudhao1999** [comment]
> 好想求这个setting panel 部分透明的代码， if 方便的话，谢谢。 我找到了插件，所有页面都透明了， 并非我想要的！ 你底部的图片有巧思~ 这个山的部分，很低调，舒适。 能不能干脆share 我css ？ Thank u so much!

GitHub不支持上传css文件，我把后缀改成了txt，你可以再改回来

**Comment by nevertoday** [comment]
thanks

**Comment by nevertoday** [comment]
真精致~  哈哈哈。 大道至简~

**Comment by nevertoday** [comment]
唯一就是不想让波浪动的这么快~ 哈哈哈

**Comment by nevertoday** [comment]
用上了，真精致！
